# Generated by Django 4.1 on 2022-08-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_photo2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="photo2",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
