# Generated by Django 4.1 on 2022-08-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_photo_alter_product_photo2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="photo", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="product", name="photo2", field=models.URLField(blank=True),
        ),
    ]
